<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <base href="<?= $this->url; ?>/">

  <title>統一帳票更新システム（プレビュー）</title>

  <!--[if lte IE 8 ]>
  <script src="js/html5.js"></script>
  <![endif]-->

<link rel="stylesheet" href="./css/global.css?">
<link rel="stylesheet" href="./css/jquery-ui.css">
<link rel="stylesheet" href="./common/css/bbnavi.css">
<link rel="stylesheet" href="./css/telnumber.css">

<script type="text/javascript" src="./js/jquery.js"></script>
<script type="text/javascript" src="./js/jquery-ui.js"></script>
<script type="text/JavaScript" src="./common/js/bbnavi.js"></script>
<script type="text/JavaScript" src="./common/js/bbnavitax.js"></script>
<script type="text/javascript" src="./js/global.js?"></script>
<script type="text/javascript" src="./js/global_layout.js"></script>
<script type="text/javascript" src="./js/global_sites.js"></script>
<!--script type="text/javascript" src="./js/global_notification.js"></script-->
<script type="text/javascript" src="./js/global_quicklink.js"></script>
<script type="text/javascript" src="./js/telnumber.js"></script>

</head>

<body>
<div class="mainmenu_parent" id="" name="layout1" style="margin:20px auto;">
  <div id="mainmenu" class="layoutitem_a ui-droppable" name="layoutitem_2">
  </div>
</div>
</body>
</html>