   <div class="site-info">
   <h3>本社統一帳票一覧</h3>
    <ul class="heightLine">
     <li>
      → <span class="icon_excel">本社統一帳票一覧(H28.07.26時点)（109KB）</span>
     </li>
    </ul>
    <div id="page-btns" class="pull">
				<button type="button" class="btn btn-warning"><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>" class="btn" data-toggle="modal" data-target="#modal-cate">本社統一帳票一覧ファイルアップロード</a></button>
	</div>

	<form action="./../report/file/receive" class="dropzone">
  <div class="fallback">
    <input name="files" type="file" multiple />
  </div>
</form>
   </div>


   <div class="newfile_area">
    <h3>最新の改訂版</h3>
    <div class="newfile-dl">
     <p class="btn_newfile"><a href="file/20160318_kaitei.zip"><span class="icon_zip">改訂版のみをダウンロード （31.5KB）</span></a></p>
    </div>
    <div id="page-btns" class="pull">
				<button type="button" class="btn btn-warning"><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>" class="btn" data-toggle="modal" data-target="#modal-cate">最新の改訂版ファイルアップロード</a></button>
				<!-- <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modal-cate">カテゴリの編集</button> -->
				<!-- <button type="button" class="btn btn-success" id="btn-save">下書き保存する</button>
				<button type="button" class="btn btn-info" id="btn-preview">プレビュー</button> -->
	</div>
   </div>
   <h2>統一帳票サイト・更新システム</h2>
	<!-- <div class="cnt-head clearfix"> -->
	<div class="clearfix">
			<div class="pull-left">
				<div id="modal-menu">
					<div class="internal">
						<ul>
							<li class="title">カテゴリ一覧
							</li>
						</ul>
					</div>
					<div class="external">
						<ul>
							<li class="title">仮公開用ページ
							</li>
						</ul>
					</div>
				</div>
			</div>
<article class="cnt cnt-690 cnt-wrap">
<table>
<tr>
<th>カテゴリ名</th>
<th></th>
</tr>
<?php foreach($this->allCategorys as $itemSheet) : ?>
<tr>
    <td><a href="ledger/ledger#h2_<?php echo $this->escape($itemSheet->id); ?>"><?php echo $this->escape($itemSheet->cateName); ?></a></td>
    <td>

        <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'edit', 'id'=>$itemSheet->id));?>" class="btn btn-warning" data-toggle="modal" data-target="#modal-cate">編集</a>
        <!-- <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'delete', 'id'=>$itemSheet->id));?>">削除</a> -->
    </td>
</tr>
<?php endforeach; ?>
</table>


				<div id="page-btns" class="pull">
				<button type="button" class="btn btn-warning"><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>" class="btn" data-toggle="modal" data-target="#modal-cate">カテゴリ新規作成</a></button>
				<!-- <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modal-cate">カテゴリの編集</button> -->
				<!-- <button type="button" class="btn btn-success" id="btn-save">下書き保存する</button>
				<button type="button" class="btn btn-info" id="btn-preview">プレビュー</button> -->
				</div>
			</div>
	<div class="cnt-bodys">
	<ul>
	<?php

	foreach ($this->allCategorys as $row){
	print '<li><a href="ledger/ledger#h2_'.$row->id.'"><img src="img/'.$row->imgName.'"'.'alt="'.$row->cateName.'"></a></li>';
	}
	?>
	<li><a href="file/20160725_2_all.zip"><img class="btn" src="img/menu_all.png" alt="一括ダウンロード"/></a><span>25.6MB</span></li>
	</ul>
	</div>
		</div>
	</div>
</article>

	<!-- categorys modal -->
<div class="modal fade" id="modal-cate" tabindex="-1" data-backdrop="static">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-body">


<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>">カテゴリ追加</a></p>
<table>
<tr>
<th>カテゴリ名</th>
<th>画像名</th>
<th>アンカー名</th>
<th>優先度</th>
<th></th>
</tr>
<?php foreach($this->allCategorys as $itemSheet) : ?>
<tr>
    <td><?php echo $this->escape($itemSheet->cateName);?></td>
    <td><?php echo $this->escape($itemSheet->imgName);?></td>
    <td><?php echo $this->escape($itemSheet->anchorName);?></td>
    <td><?php echo $this->escape($itemSheet->priority);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'editLedger', 'id'=>$itemSheet->id));?>">編集</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<button type="button" id="cate-btn-add" class="btn btn-default">カテゴリの追加</button>

<!-- <?= $this->render('parts/edit.phtml') ?> -->


			</div>
<!-- 			<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
	<button type="button" class="btn btn-success" id="cate-btn-reflect">反映する</button>
</div> -->
		</div>
	</div>
</div>


<!-- end of categorys modal -->