<div class="pagelink firstChild">
    <ul class="firstChild">
    <?php foreach($this->allCategory as $category) : ?>
     <li>
     <a href="#h2_<?php echo $this->escape($category['id']); ?>" class="firstChild lastChild"><?php echo $this->escape($category['cateName']); ?></a>
     </li>
     <?php endforeach; ?>
    </ul>

   </div>

<!-- 各カテゴリのヘッダを記述 -->
<?php foreach($this->allCategory as $category) : ?>

<div style="margin-bottom:15px">
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modal-cate3">
新規帳票追加</button>

<button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-pre">
プレビュー</button>
</div>
<small>*ドラッグで行の順番を入れ替えることが出来ます。</small>
<h2 id="h2_<?php echo $this->escape($category['id']); ?>"><?php echo $this->escape($category['cateName']); ?></h2>
    <p><?php echo $this->escape($category['remarks']); ?></p>

<form name="editledger" action="" method="post" class="editledger">
    <input type="button" name="button" class="submitbtn2 btn btn-primary" value="仮編集を保存">
<table>
<thead>
  <tr class="">
  <th>背景</th>
  <th>連番</th>
  <th class="cellwidth393">帳票名</th>
  <th>更新日</th>
  <th style="width:120px;">ファイル</th>
  <th style="width: 70px;">表示設定</th>
  <th></th>
</tr>
</thead>
<tbody class="jquery-ui-sortable">

<!-- 各カテゴリの帳票行を追加 -->
<?php foreach ($this->allLedgers[$category['id']] as $led ): ?>
<?php
  if (!$led['itemId']) {
    // itemIdが空なら次の行へ
    continue;
  }
?>
<tr data-id="<?php echo $led['itemId']; ?>"
<?php if($led['display'] == 1){

  if($led['bgColor'] == ''){
    echo 'style="background: #dfdfdf"';
  } else {
    echo 'style="background:'. $led['bgColor'].'"';
  }

}; ?>>
  <td>
    <input type="hidden" name="itemId[]" value="<?= $led['itemId'] ?>">
    <input type="hidden" name="bgColor[]" class="bgColor" value="<?= $led['bgColor'] ?>" data-id="bgColor-<?php echo $led['itemId']; ?>">
  </td>
	<td>
	<input type="hidden" name="idCategory[]" value="<?= $led['idCategory'] ?>" >
	<input type="text" name="idLedger[]" class="idLedger" value="<?= $led['idLedger'] ?>" maxlength="6" style="width:70px;">
	</td>
	<td>
	<input type="text" name="ledgerName[]" value="<?= $led['ledgerName'] ?>" style="width: 310px; margin-bottom: 5px;">
        <button class="add-title">*注釈追記</button>
        <div class="add-wrap">
	<input type="hidden" name="color[]" class="color" value="<?= $led['color'] ?>" data-id="color-<?php echo $led['itemId']; ?>">

            *注釈:<input type="text" name="annotation[]" class="annotation" value="<?= $led['annotation'] ?>" >
            </div>
	</td>
	<td>

	<input type="text" name="dateUpdate[]" class="form-control datepicker dateUpdate" value="<?= date('Y/m/d', strtotime($led['dateUpdate'])); ?>" style="width:70px;">
	</td>
	<td>
    <span class="ledgerFileName" style="width:120px;white-space: nowrap;overflow: hidden;"><?= $led['ledgerFile'] ?></span>
  	<input type="hidden" name="ledgerFile[]" value="<?= $led['ledgerFile'] ?>" class="ledgerFile">
  	<input type="hidden" name="fileSize[]" value="<?= $led['fileSize'] ?>" class="fileSize">


    <input name="uf1" type="file" class="btn-info ledgerFiles uf1">
<!--    <input type="button" value="アップロード" class="btn_up2">-->
	</td>
	<td>
  <select name="display[]" class="display">
    <option value="0" <?php if($led['display'] == 0){ echo "selected";} ?>>表示</option>
    <option value="1" <?php if($led['display'] == 1){ echo "selected";} ?>>非表示</option>
  </select>
        <p class="h_comment">
        コメント<input type="text" name="comment[]" class="comment" value="<?= $led['comment'] ?>" class="" style="width: 50px;">
        </p>
	</td>
	<td>
        <botton>
	<a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'delete', 'itemId'=>$led['itemId']));?>" class="btn btn-danger">
    <?= ($led['deleted'] == 0) ? "削除" : "取り消し" ?>
  </a>
        </botton>
    </td>
	</tr>

<?php endforeach; ?>

</tbody>
</table>
</form>
<div class="pagetop"><a href="#container">ページトップへ</a></div>

<?php endforeach; ?>

<!-- ファイルアップロード用フォーム -->
<form enctype="multipart/form-data" action="<?php echo $this->url(array('controller'=>'File','action'=>'receive'));?>" method="POST" class="form2">
  <input type="hidden" name="fileup" value="" id="fileup2">
</form>

<script type="text/javascript">
$(function(){

// カラーパレット選択設定
    $('.color').paletteColorPicker({
    colors: [
      {"#FF3366": "#FF3366"},
      {"#E04F9B": "#E04F9B"},
      {"#727272": "#727272"}
    ],
    position: 'upside' // default -> 'upside'
  });

   $('.bgColor').paletteColorPicker({
    colors: [
      {"#FCFBEF": "#FCFBEF"},
      {"#DFDFDF": "#DFDFDF"}
    ],
    position: 'upside' // default -> 'upside'
  });


//削除設定
      $(".btn_del").on('click', function() {

        if(!confirm("削除しますか？")) {
                return false;
            }
          });
// ファイルアップロード設定
      $(".uf1").on('change', function() {

        if(!confirm("アップロードしますか？")) {
                return false;

            } else {

        // 親の要素を取得
        var $parent = $(this).closest('tr');

        var formData = new FormData();
        formData.append("uploadFile", $parent.find('.ledgerFiles').get(0).files[0]);
        formData.append("idCategory", $parent.find('input[name="idCategory[]"]').val());

        $.ajax({
            url: $($('.form2')).attr('action'),
            type:'POST',
            enctype  : 'multipart/form-data',
            processData: false,
            contentType: false,
            dataType: 'json',
            // サーバに送信するデータ
            data : formData
        }).then(
          function(data) {
            $parent.find('.ledgerFile').val(data.filename);
            $parent.find('.fileSize').val(data.filesize);
            $parent.find('.ledgerFileName').text(data.filename);
          },
          function(XMLHttpRequest, textStatus, errorThrown) {
            alert('ファイルのアップロードに失敗しました。');
          }
        );

      }
      });

// ajax通信設定
  $('.submitbtn2').on('click', function() {
    var $form = $(this).closest('form');

    if (!confirm("更新しますか？")) {
      return false;
    }

    var hostUrl = './../ledger/changeledger';

    // var formData = new FormData($(this).closest('form')[0]);

    // // formDataに必要な要素を登録
    // formData.append("itemId", $parent.data('id'));
    // formData.append("idCategory", $parent.find('input[name="idCategory[]"]').val());
    // formData.append("idLedger", $parent.find('input[name="idLedger[]"]').val());
    // formData.append("ledgerName", $parent.find('input[name="ledgerName[]"]').val());
    // formData.append("color", $parent.find('input[name="color[]"]').val());
    // formData.append("annotation", $parent.find('input[name="annotation[]"]').val());
    // formData.append("bgColor", $parent.find('input[name="bgColor[]"]').val());
    // formData.append("dateUpdate", $parent.find('input[name="dateUpdate[]"]').val());
    // formData.append("ledgerFile", $parent.find('input[name="ledgerFile[]"]').val());
    // formData.append("fileSize", $parent.find('input[name="fileSize[]"]').val());
    // formData.append("display", $parent.find('select[name="display[]"]').val());
    // formData.append("comment", $parent.find('input[name="comment[]"]').val());

    $.ajax({
        url: hostUrl,
        type:'POST',
        dataType: 'json',
        data : $form.serialize()
        // data : formData
    }).then(
      function(res) {
        // エラーあり
        if (res.error) {
          return;
        }

        // 更新完了
        alert("更新しました");

        // 更新色を削除
        $form.find('.changed').removeClass('changed');

        console.log(res);        
        /*window.location.reload();*/
      },
      function(XMLHttpRequest, textStatus, errorThrown) {
        alert("更新に失敗しました");
      }
    );
  });



  // 並び替え終了時のイベント
  $( ".jquery-ui-sortable" ).on( "sortupdate", function( event, ui ) {
    var $tbody = $(event.target);
    var len = $tbody.find('tr').length;
    var formData = {};
    $tbody.find('tr').each(function(i) {
      var $tr = $(this);
      console.log('itemId = ' + $tr.data('id') + ' ' + 'index = ' + i + ' priority = ' + (len - i));

      formData[i] = {
        itemId: $tr.data('id'),
        priority: (len - i)
      };
    });

    $.ajax({
        url: './../ledger/sort',
        type:'POST',
        dataType: 'json',
        // contentType: 'application/json',
        // サーバに送信するデータ
        data : {'list': formData}
    }).then(
      function(data) {
        // 成功した時は画面を更新する
        alert('並び替えが完了しました');
      },
      function(XMLHttpRequest, textStatus, errorThrown) {
        alert('並び替えに失敗しました。');
      }
    );

  } );

  $('.public').on('click', function() {

    if(!confirm("本番反映しますか？")) {
      return false;

    }
  });
  $('.reset').on('click', function() {

    if(!confirm("リセットしますか？")) {
      return false;

    }
  });
//    注釈アコーディオン

    $('.add-title').on('click', function(e) {
        $(this).next('.add-wrap').slideToggle('fast');
        e.preventDefault();
    });

    var $arr_dis = $('editledger').find('select[name="display[]"]').val();
    var $comment = $('editledger').find('p.h_comment]');

    console.log($arr_dis);
    console.log($comment);

    if($arr_dis == 0){
        $('editledger').find('p.h_comment]').hide();
    } else {
        $('editledger').find('p.h_comment]').show();

    }

    $('.display').on('change', function(e){

        var $parent = $(this).closest('tr');
        var $selectDis = $parent.find('select[name="display[]"]').val();

        if($selectDis == 0){
            $parent.find('p.h_comment').hide();

        } else {

            $parent.find('.h_comment').show();

        }
        e.preventDefault();
    });
    // 画面読み込み時に一度実行
    $('.display').trigger('change');

    // 指定要素の親のth or tdに changed クラスを付与する
    function markChanged(el) {
      $(el).closest('td,th').addClass('changed');
    }

    $(document).on('change', 'table input', function() {
      markChanged(this);
    });
});
</script>

<style>
  .changed {
    background-color: #fdd;
  }
</style>




<!-- add ledger modal -->
<div class="modal" id="modal-cate3" tabindex="-1" data-backdrop="static">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

<div class="modal-body">



<?= $this->render('./parts/addledger.phtml') ?>


			</div>
		</div>
	</div>
</div>


<!-- end of add ledger modal -->


<div class="modal" id="modal-pre" tabindex="-1" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-footer">
        <button type="button"><a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'publish'));?>" class="btn btn-danger public">本番反映</a></button>
        <button type="button"><a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'reset'));?>" class="btn btn-default reset">リセット</a></button>
            <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        </div>
      <div class="modal-body">

<iframe src="http://10.56.164.60/dev/morinaga/web/html/staging/unified_report/detail.html" class="pre_ledger"></iframe>


      </div>
    </div>
  </div>
</div>