<div class="pagelink firstChild">
    <ul class="firstChild">
    <?php foreach($this->allCategory as $category) : ?>
     <li>
     <a href="#h2_<?php echo $this->escape($category['id']); ?>" class="firstChild lastChild"><?php echo $this->escape($category['cateName']); ?></a>
     </li>
     <?php endforeach; ?>
    </ul>

   </div>

<?php foreach ($this->rows as $val1) : { ?>

	<?php foreach ($val1 as $categories ) ?>
<div style="margin-bottom:15px">
<button type="button" class="btn">
<a href="<?php echo $this->url(array('controller'=>'ledger', 'action'=>'addledger'));?>" data-toggle="modal" data-target="#modal-cate3" ><?php echo $this->escape($itemSheet->cateName); ?>新規帳票追加</a></button>

<button type="button" class="btn" data-toggle="modal" data-target="#modal-pre">
プレビュー</button>
</div>
<small>*ドラッグで行の順番を入れ替えることが出来ます。</small>
<h2 id="h2_<?php echo $this->escape($categories['idCategory']); ?>"><?php echo $this->escape($categories['cateName']); ?></h2>
    <p><?php echo $this->escape($categories['remarks']); ?></p>
<table>
<thead>
  <tr class="">
  <th>背景</th>
  <th>連番</th>
  <th class="cellwidth393">帳票名</th>
  <th>更新日</th>
  <th style="width:120px;">ファイル</th>
  <th style="width: 70px;">表示設定</th>
  <th></th>
</tr>
</thead>
<tbody class="jquery-ui-sortable">
<?php foreach ($val1 as $categories ) : { ?>

<tr data-id="<?php echo $categories['itemId']; ?>"
<?php if($categories['display'] == 1){

  if($categories['bgColor'] == ''){
    echo 'style="background: #dfdfdf"';
  } else {
    echo 'style="background:'. $categories['bgColor'].'"';
  }

}; ?>>
    <form name="editledger" enctype="multipart/form-data" action="" method="post" class="editledger">
  <td><input type="hidden" name="bgColor" class="bgColor" value="<?= $categories['bgColor'] ?>" data-id="bgColor-<?php echo $categories['itemId']; ?>"></td>
	<td>
	<input type="hidden" name="idCategory" value="<?= $categories['idCategory'] ?>" ><br><br>
	<input type="text" name="idLedger" class="idLedger" value="<?= $categories['idLedger'] ?>" maxlength="6" style="width:70px;">
	</td>
	<td>
	<input type="text" name="ledgerName" value="<?= $categories['ledgerName'] ?>" style="width: 310px; margin-bottom: 5px;">
        <button class="add-title">*注釈追記</button>
        <div class="add-wrap">
	<input type="hidden" name="color" class="color" value="<?= $categories['color'] ?>" data-id="color-<?php echo $categories['itemId']; ?>">

            *注釈:<input type="text" name="annotation" class="annotation" value="<?= $categories['annotation'] ?>" >
            </div>
	</td>
	<td>

	<input type="text" name="dateUpdate" class="form-control datepicker dateUpdate" value="<?= $categories['dateUpdate'] ?>" style="width:70px;">
	</td>
	<td>
	<input type="text" name="ledgerFile" value="<?= $categories['ledgerFile'] ?>" class="ledgerFile" style="width:120px;">
	<input type="hidden" name="fileSize" value="<?= $categories['fileSize'] ?>" class="fileSize"><br>


    <input name="uf1" type="file" class="btn-info ledgerFiles uf1">
<!--    <input type="button" value="アップロード" class="btn_up2">-->
	</td>
	<td>
  <select name="display" class="display">
    <option value="0" <?php if($categories['display'] == 0){ echo "selected";} ?>>表示</option>
    <option value="1" <?php if($categories['display'] == 1){ echo "selected";} ?>>非表示</option>
  </select>
        <?php if($categories['display'] == 0){ echo "<p style='display: none;'>";} else {echo "<p>";} ?>
        コメント<input type="text" name="comment" class="comment" value="<?= $categories['comment'] ?>" class="" style="width: 50px;">
        </p>
	</td>
	<td>
	<input type="button" name="button" class="submitbtn2" value="仮編集を保存">
        <botton class="btn btn_del">
	<a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'delete', 'itemId'=>$categories['itemId']));?>">
<?php if($categories['display'] == 0){
  echo "削除";
} else {
  echo "取り消し";
} ?>
  </a>
        </botton>
    </td>
    </form>
    <form enctype="multipart/form-data" action="<?php echo $this->url(array('controller'=>'File','action'=>'receive'));?>" method="POST" class="form2">
        <input type="hidden" name="fileup" value="" id="fileup2">
    </form>
	</tr>

<?php } ?>

<?php endforeach; ?>
</tbody>
</table>
<div class="pagetop"><a href="#container">ページトップへ</a></div>
<?php } ?>

<?php endforeach; ?>


<script type="text/javascript">
$(function(e){



// カラーパレット選択設定
    $('.color').paletteColorPicker({
    colors: [
      {"#FF3366": "#FF3366"},
      {"#E04F9B": "#E04F9B"},
      {"#727272": "#727272"}
    ],
    position: 'upside' // default -> 'upside'
  });

   $('.bgColor').paletteColorPicker({
    colors: [
      {"#FCFBEF": "#FCFBEF"},
      {"#DFDFDF": "#DFDFDF"}
    ],
    position: 'upside' // default -> 'upside'
  });


//削除設定
      $(".btn_del").on('click', function() {

        if(!confirm("削除しますか？")) {
                return false;
            }
          });
// ファイルアップロード設定
      $(".uf1").on('change', function() {

        if(!confirm("アップロードしますか？")) {
                return false;

            } else {

        // 親の要素を取得
        var $parent = $(this).closest('tr');

        var formData = new FormData();
        formData.append("uploadFile", $parent.find('.ledgerFiles').get(0).files[0]);
        formData.append("idCategory", $parent.find('input[name=idCategory]').val());

        $.ajax({
            url: $($('.form2')).attr('action'),
            type:'POST',
            enctype  : 'multipart/form-data',
            processData: false,
            contentType: false,
            dataType: 'json',
            // サーバに送信するデータ
            data : formData
        }).then(
          function(data) {
            $parent.find('.ledgerFile').val(data.filename);
            $parent.find('.fileSize').val(data.filesize);
          },
          function(XMLHttpRequest, textStatus, errorThrown) {
            alert('ファイルのアップロードに失敗しました。');
          }
        );

      }
      });

// ajax通信設定
  $('.submitbtn2').on('click', function() {

            if(!confirm("更新しますか？")) {
              return false;

            }else{

            // 親の要素を取得
            var $parent = $(this).closest('tr');

            var hostUrl= './../ledger/editledger';
            var formData = new FormData($('.editledger')[0]);

            // formDataに必要な要素を登録
            formData.append("itemId", $parent.data('id'));
            formData.append("idCategory", $parent.find('input[name=idCategory]').val());
            formData.append("idLedger", $parent.find('input[name=idLedger]').val());
            formData.append("ledgerName", $parent.find('input[name=ledgerName]').val());
            formData.append("color", $parent.find('input[name=color]').val());
            formData.append("annotation", $parent.find('input[name=annotation]').val());
            formData.append("bgColor", $parent.find('input[name=bgColor]').val());
            formData.append("dateUpdate", $parent.find('input[name=dateUpdate]').val());
            formData.append("ledgerFile", $parent.find('input[name=ledgerFile]').val());
            formData.append("fileSize", $parent.find('input[name=fileSize]').val());
            formData.append("display", $parent.find('select[name=display]').val());
            formData.append("comment", $parent.find('input[name=comment]').val());

            $.ajax({
                url: hostUrl,
                type:'POST',
                enctype  : 'multipart/form-data',
                processData: false,
                contentType: false,
                dataType: 'json',
                // サーバに送信するデータ
                data : formData
                }).then(
                function(formData) {
                  alert("更新しました");
                    window.location.reload();
                },
                function(XMLHttpRequest, textStatus, errorThrown) {
                             alert("更新に失敗しました");
                       });
              }
        });



  // 並び替え終了時のイベント
  $( ".jquery-ui-sortable" ).on( "sortupdate", function( event, ui ) {
    var $tbody = $(event.target);
    var len = $tbody.find('tr').length;
    var formData = {};
    $tbody.find('tr').each(function(i) {
      var $tr = $(this);
      console.log('itemId = ' + $tr.data('id') + ' ' + 'index = ' + i + ' priority = ' + (len - i));

      formData[i] = {
        itemId: $tr.data('id'),
        priority: (len - i)
      };
    });

    $.ajax({
        url: './../ledger/sort',
        type:'POST',
        dataType: 'json',
        // contentType: 'application/json',
        // サーバに送信するデータ
        data : {'list': formData}
    }).then(
      function(data) {
        // 成功した時は画面を更新する
        alert('並び替えが完了しました');
      },
      function(XMLHttpRequest, textStatus, errorThrown) {
        alert('並び替えに失敗しました。');
      }
    );

  } );

  $('.public').on('click', function() {

    if(!confirm("本番反映しますか？")) {
      return false;

    }
  });
  $('.reset').on('click', function() {

    if(!confirm("リセットしますか？")) {
      return false;

    }
  });

    $('.add-title').on('click', function(e) {
        $(this).next('.add-wrap').slideToggle('fast');
        e.preventDefault();
    });

    e.preventDefault();

});
</script>





<!-- add ledger modal -->
<div class="modal fade" id="modal-cate3" tabindex="-1" data-backdrop="static">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

<div class="modal-body">



<?= $this->render('./parts/addledger.phtml') ?>


			</div>
		</div>
	</div>
</div>


<!-- end of add ledger modal -->


<div class="modal fade" id="modal-pre" tabindex="-1" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-footer">
        <button type="button" class="btn btn-default public"><a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'publish'));?>">本番反映</a></button>
        <button type="button" class="btn btn-default reset"><a href="<?php echo $this->url(array('controller'=>'ledger',
            'action'=>'reset'));?>">リセット</a></button>
            <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        </div>
      <div class="modal-body">

<iframe src="./stage/detail.html" class="pre_ledger"></iframe>


      </div>
    </div>
  </div>
</div>