<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h6 class="modal-title">新規カテゴリ追加</h6>
			</div>
<div class="modal-body">
<form id="category" name="category" enctype="application/x-www-form-urlencoded" action="" method="post">


<p id="id-element">
<input type="hidden" name="id" value="<?= $this->category['id'] ?>" id="id">
</p>
<fieldset>
<legend id="cateName-label"><label for="cateName" class="required">カテゴリ名</label><small class="req">*必須</small></legend>
<p id="cateName-element">
<input type="text" name="cateName" id="cateName" value="<?= $this->category['cateName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="imgName-label"><label for="imgName" class="required">画像名</label><small class="req">*必須</small></legend>
<p id="imgName-element">
<input type="text" name="imgName" id="imgName" value="<?= $this->category['imgName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="anchorName-label"><label for="anchorName" class="required">アンカー名</label><small class="req">*必須</small></legend>
<p id="anchorName-element">
<input type="text" name="anchorName" id="anchorName" value="<?= $this->category['anchorName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="priority-label"><label for="priority" class="">優先度</label></legend>
<p id="priority-element">
<input type="text" name="priority" id="priority" value="<?= $this->category['priority'] ?>"></p>
</fieldset>

<fieldset>
<legend id="priority-label"><label for="dir" class="">帳票カテゴリ別ディレクトリ</label><small class="req">(※必須、半角英数字、8文字以内)</small></legend>
<p id="priority-element">
<input type="text" name="dir" id="dir" value="<?= $this->category['dir'] ?>"></p>
</fieldset>

<legend id="remarks-label"><label for="remarks" class="">カテゴリー備考</label><small>帳票カテゴリー備考</small></legend>
<p id="remarks-element">
<input type="text" name="remarks" id="remarks" value="<?= $this->category['remarks'] ?>" class="cellwidth330"></p>
</fieldset>

<p id="submit-element" class="mt15 tac">
<input type="button" name="submit" id="submitbtn" value="新規カテゴリ追加" class="btn btn-primary">
</p>
</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
</div>

<script type="text/javascript">


	$('#submitbtn').on('click', function() {

        if(!confirm("新規カテゴリ追加しますか？")) {
            return false;
        }

        var hostUrl= './index/add';
        var data = {
        	id : $('#id').val(),
        	cateName : $('#cateName').val(),
        	imgName : $('#imgName').val(),
        	anchorName : $('#anchorName').val(),
        	priority : $('#priority').val(),
            dir : $('#dir').val()
        };

        $.ajax({
            url: hostUrl,
            type:'POST',
            dataType: 'json',
            // サーバに送信するデータ
            data : data
        })
        .then(
            function(res) {
                if (res.error) {
                  // エラーメッセージ res.messages を何らか出力
                  var displayMessage = 'エラーがあります\n\n';
                  $.each(res.messages, function(key, msg) {
                    // メッセージが空でなければ追加
                    if (msg !== '') {
                      displayMessage += msg + '\n';
                    }
                  });
                  alert(displayMessage);
                  return;
                }

                // エラーがない場合、画面をリロード
                alert("新規カテゴリを追加しました");
                window.location.reload();
            },
            function(XMLHttpRequest, textStatus, errorThrown) {
                alert("新規カテゴリ追加に失敗しました");
            }
        );
    });


</script>