<!-- カテゴリー追加・編集モーダル画面 -->
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h6 class="modal-title">カテゴリの編集</h6>
</div>

<div class="modal-body">
<form id="category" name="category" enctype="application/x-www-form-urlencoded" action="" method="post">
<p id="id-element">
<input type="hidden" name="id" value="<?= $this->category['id'] ?>" id="id"></p>

<fieldset>
<legend id="cateName-label"><label for="cateName" class="required">カテゴリ名</label></legend>
<p id="cateName-element">
<input type="text" name="cateName" id="cateName" value="<?= $this->category['cateName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="imgName-label"><label for="imgName" class="required">画像名</label></legend>
<p id="imgName-element">
<input type="text" name="imgName" id="imgName" value="<?= $this->category['imgName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="anchorName-label"><label for="anchorName" class="required">アンカー名</label></legend>
<p id="anchorName-element">
<input type="text" name="anchorName" id="anchorName" value="<?= $this->category['anchorName'] ?>"></p>
</fieldset>

<fieldset>
<legend id="priority-label"><label for="priority" class="">優先度</label></legend>
<p id="priority-element">
<input type="text" name="priority" id="priority" value="<?= $this->category['priority'] ?>"></p>
</fieldset>

<fieldset>
<legend id="priority-label"><label for="dir" class="">帳票カテゴリ別ディレクトリ</label>(※必須、半角英数字、8文字以内)</legend>
<p id="priority-element">
<input type="text" name="dir" id="dir" value="<?= $this->category['dir'] ?>"></p>
</fieldset>

<p id="submit-element" class="mt15 tac">
<input type="button" name="submit" id="submitbutton" value="編集を保存" class="btn btn-primary"></p>
</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
</div>

<script type="text/javascript">
$(function(){

	$('#submitbutton').on('click', function() {
    if(!confirm("更新しますか？")) {
      return false;
    }

    var hostUrl = './index/edit';
    var formData = new FormData($('#category')[0]);

    $.ajax({
      url: hostUrl,
      type:'POST',
      enctype  : 'multipart/form-data',
      processData: false,
      contentType: false,
      dataType: 'json',
      // サーバに送信するデータ
      data : formData
    }).then(
      function(res) {
        if (res.error) {
          // エラーメッセージ res.messages を何らか出力
          var displayMessage = 'エラーがあります\n\n';
          $.each(res.messages, function(key, msg) {
            // メッセージが空でなければ追加
            if (msg !== '') {
              displayMessage += msg + '\n';
            }
          });
          alert(displayMessage);
          return;
        }

        // エラーがない場合、画面をリロード
        alert("更新しました");
        window.reload();
      },
      function(XMLHttpRequest, textStatus, errorThrown) {
        alert("更新に失敗しました");
      });
    });

});
</script>